tasks/urls.py
from django.conf.urls import url

from . import views

app_name = 'tasks'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail' ),
    url(r'^add/$', views.TaskAdd.as_view(), name='task_add'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.TaskUpdate.as_view(), name='task_update'),
    #url(r'^(?P<pk>[0-9]+)/delete/$', views.TaskDelete.as_view(), name='task_delete'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

todo/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tasks/', include('tasks.urls')),
]

tasks/models.py
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db import models


class Task(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	description = models.CharField(max_length=500)
	complete = models.BooleanField(default=False)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('tasks:detail', kwargs={'pk' : self.pk})

tasks/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Task

class LoginForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'password']

class RegisterForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'email', 'password'];

class TaskForm(forms.ModelForm):

	class Meta:
		model = Task
		fields = ['title', 'description', 'complete'];

tasks/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import logout
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.views import generic
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import UpdateView
from django.views.generic import View

from .forms import LoginForm
from .forms import TaskForm
from .forms import RegisterForm
from .models import Task

class IndexView(LoginRequiredMixin, generic.ListView):
	template_name = 'tasks/index.html'
	login_url = '/tasks/login/'

	def get_queryset(self):
		return Task.objects.filter(user=self.request.user)

	def get_user(self):
		return queryset.get(user=self.request.user)

class DetailView(LoginRequiredMixin, generic.DetailView):
	model = Task
	login_url = '/tasks/login/'
	template_name = 'tasks/detail.html'

	def get(self, request, pk):
		#import ipdb;ipdb.set_trace()
		task = get_object_or_404(Task, pk=pk, user=self.request.user)
		return render(request, self.template_name, {'task' : task})

	def post(self, request, *args, **kwargs):
		if "update" in request.POST:
			return HttpResponseRedirect('/tasks/' + str(kwargs['pk']) + '/update')
		elif "delete" in request.POST:
			task = get_object_or_404(Task, pk=kwargs['pk'], user=self.request.user)
			task.delete()
			return redirect('tasks:index')# + str(kwargs['pk']) + '/delete')

class TaskAdd(LoginRequiredMixin, CreateView):
	model = Task
	login_url = '/tasks/login/'
	fields = ['title', 'description']

	def form_valid(self, form):
		task = form.save(commit=False)
		task.user = self.request.user
		task.save()
		return redirect(task.get_absolute_url())

class TaskUpdate(LoginRequiredMixin, View):
	form_class = TaskForm
	login_url = '/tasks/login/'
	template_name = 'tasks/task_form.html'

	def get(self, request, pk):
		task = Task.objects.get(pk=pk)
		form = self.form_class(instance=task)
		return render(request, self.template_name, {'form' : form})

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)
		if form.is_valid():
			get_object_or_404(Task, pk=kwargs['pk'], user=self.request.user)
			task = form.save(commit=False)
			task.user = request.user
			task.id = kwargs['pk']
			task.save()
			return HttpResponseRedirect('/tasks/' + str(kwargs['pk']))
		return render(request, self.template_name, {'form' : form}) 

class LoginView(View):
	form_class = LoginForm
	template_name = 'tasks/login.html'

	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form' : form})

	def post(self, request):
		form = self.form_class(request.POST)

		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return redirect('tasks:index')

		return render(request, self.template_name, {'form' : form})

def logout_view(request):
	logout(request)
	return redirect('tasks:login')

class RegisterView(View):
	form_class = RegisterForm
	template_name = 'tasks/register.html'

	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form' : form})

	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():
			user = form.save(commit=False)
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect('tasks:index')

		return render(request, self.template_name, {'form' : form})

tasks/templates/tasks/base.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!--<link rel="stylesheet" type="text/css" href="{% static 'tasks/style.css' %}"-->

<title>
	{% block title %}
	{% endblock %}	
</title>

<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="{% url 'tasks:index' %}">Home</a>
			<a class="navbar-brand" href="{% url 'tasks:task_add' %}">Add task</a>
		</div>
		<div class="navbar-right">
			<a class="navbar-brand" href="{% url 'tasks:logout' %}">Logout</a>
	</div>
</nav>

<head>
	<div class="container">
		<div style="margin-left:20px;">
			<h4>
				{% block head %}
				{% endblock %}
			</h4>
	 	</div>
 	</div>
</head>

<body>
	<div class="jumbotron vertical-center">
 		<div class="container">
		 	{% block content %}
		 	{% endblock %}
 		</div>
 	</div>
</body>

tasks/templates/tasks/detail.html
{% extends 'tasks/base.html' %}

{% block title %} Task details {% endblock %}
{% block head %} Task details for: {{task.id}} {% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post">
						{% csrf_token %}
						<div class="form-group">
							<div class="col-sm-10">
								<h4>Title:{{ task.title }}</h4>
								<h5>description:{{ task.description }}</h5>
								<h5>Complete:{{ task.complete }}</h5>
								<button type="submit" name="update" class="btn btn-primary">Edit</button>
								<button type="submit" name="delete" class="btn btn-warning">Delete</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

tasks/templates/tasks/form_template.html
{% for item in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ item.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ item.label_tag }} </label>
		<div class="col-sm-10">{{ item }}</div>
	</div>
{% endfor %}

tasks/templates/tasks/index.html
{% extends "tasks/base.html" %}

{% load static %}

{% block title %} Tasks {% endblock %}
{% block head %} Tasks for {{ request.user }}: {% endblock %}

{% block content %}
	<ul>
		{% for task in object_list %}
			<li><a href="{% url 'tasks:detail' task.id %}">{{ task.title }} </a>{% if task.complete %}<img src = "{% static  'tasks/img/complete_12x16.png' %}" />{% endif %}</li>
		{% endfor %}
	</ul>
{% endblock %}

tasks/templates/tasks/login.html
{% extends 'tasks/base.html' %}

{% block title %} Login User {% endblock %}
{% block head %} Please log in {% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post">
						{% csrf_token %}
						{% include 'tasks/form_template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
					Not registered? <a href="{% url 'tasks:register' %}"> Register now<a/>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

tasks/templates/tasks/register.html
{% extends 'tasks/base.html' %}

{% block title %} User registration {% endblock %}
{% block head %} User registration {% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post">
						{% csrf_token %}
						{% include 'tasks/form_template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

tasks/templates/tasks/task_form.html
{% extends 'tasks/base.html' %}

{% block title %} Task edit{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post">
						{% csrf_token %}
						{% for item in form %}
							<div class="form-group">
								<div class="col-sm-offset-2 col-sm-10">
									<span class="text-danger small">{{ item.errors }}</span>
								</div>
								<label class="control-label col-sm-2">{{ item.label_tag }} </label>
								<div class="col-sm-10">{{ item }}</div>
							</div>
						{% endfor %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}